version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2182:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports: 
      - "9093:9092"
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  app:
    build: .
    ports:
     - "5000:5000"
    depends_on:
     - kafka
    restart: always
